### PR TITLE
Add keys conversion from ed25519 (sign keys) to curve25519 (box keys)

### PR DESCRIPTION
**Pull request by blavenie**
This pull request expose functions `crypto_sign_ed25519_sk_to_curve25519` and `crypto_sign_ed25519_pk_to_curve2551`

(functions used an Unhosted JS application : [Cesium](https://github.com/duniter/cesium))

### CODE REVIEW

**Comment by hoffmabc** [comment]
Bump?

**Comment by hoffmabc** [comment]
@tonyg is there any reason why this is being held up specifically?

**Comment by tonyg** [comment]
Hi! Sorry for the delay. No reason other than a lack of time.

Would you mind writing a few tests for the new functions, please? If possible, it'd be nice to lift the exact test cases from e.g. libsodium itself, to demonstrate the expected compatibility.

**Comment by catbref** [comment]
The corresponding tests in libsodium are at:
https://github.com/jedisct1/libsodium/blob/master/test/default/ed25519_convert.c
and
https://github.com/jedisct1/libsodium/blob/master/test/default/ed25519_convert.exp

Really hope you can merge this and produce v1.3.3 as I'm having a horrible time of trying to build this myself.

**Comment by tonyg** [comment]
Thanks for those links, @catbref. The PR is missing tests and documentation; one good next step would be to take the tests you linked and write analogous js-nacl tests.

**Comment by catbref** [comment]
Just to clarify, I couldn't modify this pull request so reworked the changes against latest master branch, added tests and created new pull request #54 

Hopefully you can merge in #54 and close this one?

**Comment by blavenie** [comment]
Close. Duplicate of !54

**Pull request closed without merging**
